FROM python:3.9-slim

RUN pip install pypiserver['passlib']

EXPOSE 8080
COPY packages /packages

RUN echo "admin:youDoNotNeedThisPasswordForTheExercise" > auth.txt

CMD ["pypi-server", "run", "-p", "8080", "-P", "auth.txt", "/packages"] 
