FROM python:3.9-slim

RUN pip install pypiserver['passlib']

COPY packages /packages

RUN echo "admin:youDoNotNeedThisPasswordForTheExercise" > auth.txt

CMD ["python", "-m", "pypiserver", "run", "-P", "auth.txt", "-p", "8080", "/packages"]

